### ISSUE TITLE
Host on Github?

### ISSUE THREAD

**Issue by bumbeishvili** [CloudCannon/vonge-jekyll-bookshop-template#5]
It's a very nice theme, it would be great if we could have a chance to host it on Github

**Comment by bglw** [comment]
Hello 👋 

Hosting directly on Github Pages won't be able to work due to their plugin limitations. 

You should be able to host this on GitHub by building it in a GitHub Action. I think the usual course of action here is to use a GitHub Action to build a Jekyll site and push it to GitHub Pages — something like https://github.com/limjh16/jekyll-action-ts or https://github.com/helaili/jekyll-action would be good places to start. It isn't a flow I have used personally, sorry, so I can't be of much more help.

**Comment by bumbeishvili** [comment]
Thank you for fast response, will give them a try

**Comment by Midnight1938** [comment]
> You should be able to host this on GitHub by building it in a GitHub Action. I think the usual course of action here is to use a GitHub Action to build a Jekyll site and push it to GitHub Pages — something like https://github.com/limjh16/jekyll-action-ts or https://github.com/helaili/jekyll-action would be good places to start. It isn't a flow I have used personally, sorry, so I can't be of much more help.

I have managed to [deploy](https://midnight1938.github.io/jekylling/) the site on github but am unable to load the theme in, any ideas?
